const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const code=html.slice(html.indexOf('/* QA 9.9.4: live, per-dynasty trophy vault. */'),html.indexOf('\nfunction careerFor('));
const context={state:{career:[{person_id:'c',coach_name:'Corey'}],programs:[{person_id:'c',coach_name:'Corey',team_name:'New Team'}],trophies:[{person_id:'c',coach_name:'Corey',season_number:1,type:'player_award',name:'Heisman Trophy'},{person_id:'c',coach_name:'Corey',season_number:1,type:'conference_championship',name:'Conference Championship'},{person_id:'c',coach_name:'Corey',season_number:2,type:'national_championship',name:'National Championship'}],heismans:[{person_id:'c',season_id:'s1',award_name:'Heisman Trophy',player_name:'Test Winner',player_position:'QB'},{person_id:'c',season_id:'s1',award_name:'Maxwell Award',player_name:'Another Winner'}],allGames:[{person_id:'c',season_number:1,team_name:'Old Team'},{person_id:'c',season_number:2,team_name:'New Team'}]},seasons:[{season_id:'s1',season_number:1,year:2026},{season_id:'s2',season_number:2,year:2027}]};
vm.createContext(context);vm.runInContext(code,context);
const awardsMenu=html.match(/<select id="heismanAward"[^>]*>([\s\S]*?)<\/select>/)[1];
const supported=[...awardsMenu.matchAll(/value="([^"]+)"/g)].map(m=>m[1]);
for(const name of supported){const art=context.sfVaultAwardArt(name);assert.ok(art,`Missing catalog entry: ${name}`);assert.ok(fs.existsSync(path.join(__dirname,'..',art.src)),`Missing artwork file: ${name}`)}
assert.equal(context.sfVaultAwardArt('Bronko Nagurski Award').id,'bronko-nagurski');
assert.equal(context.sfVaultAwardArt('Lombardi Award').id,'rotary-lombardi');
assert.equal(context.sfVaultAwardArt('Davey O’Brien Award').id,'davey-obrien');
assert.equal(context.sfVaultAwardArt('Shaun Alexander Award').id,'shaun-alexander');
assert.equal(context.sfVaultAwardArt('An Unfamiliar Future Award'),null);
let model=context.sfVaultModel();
assert.equal(model.entries.length,4,'Award view and player award details must count once');
const heisman=model.entries.find(x=>x.name==='Heisman Trophy');
assert.equal(heisman.player_name,'Test Winner');assert.equal(heisman.year,2026);assert.equal(heisman.team_name,'Old Team','Awards follow the team at award time');
assert.equal(model.entries.filter(x=>x.category==='national').length,1);
assert.equal(model.entries.filter(x=>x.category==='conference').length,1);
assert.equal(model.entries.filter(x=>x.category==='award').length,2);
context.state.programs[0].team_name='Third Team';
assert.equal(context.sfVaultModel().entries.find(x=>x.name==='Heisman Trophy').team_name,'Old Team');
context.state.trophies.push({person_id:'c',season_number:2,type:'bowl_championship',name:'Bowl Victory'});
assert.equal(context.sfVaultModel().entries.length,5,'New live records must update the collection');
context.state={career:[],programs:[],trophies:[],heismans:[],allGames:[]};
assert.equal(context.sfVaultModel().entries.length,0,'Switching leagues must clear old records');
// Spreadsheet imports use recipient_name and metadata, while RPC details may be null.
context.state={career:[],programs:[],allGames:[],trophies:[{id:'jet1',person_id:'coach1',coach_name:'Coach',season_id:'s1',type:'player_award',name:'Jet Award',recipient_name:'Return Winner',metadata:{team:'Historical Team',position:'KR'}}],heismans:[{award_id:'jet1',person_id:'coach1',coach_name:'Coach',season_id:'s1',award_name:'Jet Award',player_name:null,team_name:'Current Team'}]};
model=context.sfVaultModel();assert.equal(model.entries.length,1);assert.equal(model.entries[0].player_name,'Return Winner');assert.equal(model.entries[0].player_position,'KR');assert.equal(model.entries[0].team_name,'Historical Team');assert.equal(model.entries[0].artworkId,'jet');
context.state.trophies=[{id:'j2',person_id:'coach1',coach_name:'Coach',season_id:'s1',type:'player_award',name:'Jet Award',metadata:{player_name:'Commissioner Winner'}}];context.state.heismans=[];
assert.equal(context.sfVaultModel().entries[0].player_name,'Commissioner Winner');
context.state.trophies=[];context.state.heismans=[{person_id:'rpcOnly',coach_name:'RPC Coach',season_id:'s1',award_name:'New Award'}];
assert.equal(context.sfVaultModel().coaches[0].key,'rpcOnly');assert.equal(context.sfVaultModel().entries[0].category,'award');
// Postseason history must be complete before full game enrichment and count once.
const postseason=[1,2,3].map(n=>({id:'b'+n,person_id:'c',coach_name:'Corey',season_number:n,status:'completed',game_type:'bowl',event_name:'Alamo Bowl',result:'W',team_name:'Texas State'}));
postseason.push({id:'cc2',person_id:'c',coach_name:'Corey',season_number:2,status:'completed',game_type:'conference_championship',event_name:'Pac-12 Championship',result:'W',team_name:'Texas State'});
postseason.push({id:'cc3',person_id:'c',coach_name:'Corey',season_number:3,status:'completed',game_type:'conference_championship',event_name:'Pac-12 Championship',result:'L',team_name:'Texas State'});
context.state={trophies:[{person_id:'c',coach_name:'Corey',season_number:1,name:'Alamo Bowl',type:'bowl_championship'},{person_id:'c',coach_name:'Corey',season_number:2,name:'Pac-12 Championship',type:'conference_championship'}],vaultPostseasonGames:postseason,allGames:[postseason[2]],games:[postseason[2]],heismans:[]};
assert.equal(context.sfVaultCoachPostseason('c').bowlWins,3);assert.equal(context.sfVaultCoachPostseason('c').bowlLosses,0);
model=context.sfVaultModel();assert.equal(model.entries.filter(x=>x.category==='bowl').length,3);assert.equal(model.entries.filter(x=>x.category==='conference').length,1);assert.equal(model.entries.length,4);
context.state.games=[{...postseason[2],result:'L'}];assert.equal(context.sfVaultCoachPostseason('c').bowlWins,2);assert.equal(context.sfVaultCoachPostseason('c').bowlLosses,1);
context.state={trophies:[],heismans:[],allGames:[],games:[],vaultPostseasonGames:[]};assert.equal(context.sfVaultModel().entries.length,0);
let syntaxCount=0;
for(const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/src=|application\/json/.test(match[1]))continue;new vm.Script(match[2]);syntaxCount++}
const img={dataset:{vaultFallback:'assets/trophy-vault/award.webp'},src:'missing.webp',getAttribute(){return this.src},replaceWith(el){this.replacement=el}};
context.document={createElement:()=>({})};context.sfVaultArtFallback(img);assert.equal(img.src,'assets/trophy-vault/award.webp');context.sfVaultArtFallback(img);assert.equal(img.replacement.textContent,'Artwork unavailable');
console.log(`Award catalog covers ${supported.length} entry-menu awards plus historical extras. Trophy vault data checks passed; ${syntaxCount} inline scripts parsed.`);
